### ISSUE TITLE
RailsアプリのAWSへのデプロイ途中のmysqlの認証プラグインのエラー

### ISSUE THREAD

**Issue by sayahaya** [sayahaya/voice_component#41]
作成したPFアプリをAWSへデプロイ作業の途中でmysqlの認証プラグインのエラーが発生し、自分なりに調べて対応してみたのですが、解決に至らずアドバイスをいただきたくお願い致します。
## 現状
RUNTEQのスパルタカリキュラムのAWSのデプロイ編https://runteq.jp/skill_categories/aws
を参考に手順を進めており、RDS, EC2インスタンス環境設定編までは完了しております。
次のアプリのデプロイ編でGitHubからアプリをSSH通信でクローン→vimでconfig/master.keyというファイルを作り、ローカルのmaster.keyの中身をコピー→config/database.yml設定→gem update bundler→bundle install　まで実施し、その後の

```
rails db:create RAILS_ENV=production
```
を実行したところ、下記エラーが発生しております。
```
Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
Couldn't create 'Voice_component_production' database. Please check your configuration.
rails aborted!
ActiveRecord::ConnectionNotEstablished: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:45:in `rescue in new_client'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:39:in `new_client'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `mysql2_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_handling.rb:283:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/mysql_database_tasks.rb:8:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/mysql_database_tasks.rb:21:in `create'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:133:in `create'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:193:in `block in create_current'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:193:in `create_current'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <main>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/command.rb:52:in `invoke'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<main>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/var/www/voice_component/bin/rails:5:in `<top (required)>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/var/www/voice_component/bin/spring:10:in `block in <top (required)>'
/var/www/voice_component/bin/spring:7:in `<top (required)>'

Caused by:
Mysql2::Error: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:40:in `new'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:40:in `new_client'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `mysql2_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_handling.rb:283:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/mysql_database_tasks.rb:8:in `connection'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/mysql_database_tasks.rb:21:in `create'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:133:in `create'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:193:in `block in create_current'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:503:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:502:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/tasks/database_tasks.rb:193:in `create_current'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <main>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/command.rb:52:in `invoke'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<main>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/var/www/voice_component/bin/rails:5:in `<top (required)>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/var/www/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/var/www/voice_component/bin/spring:10:in `block in <top (required)>'
/var/www/voice_component/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

```

## 試したこと
エラーログの”Authentication plugin 'caching_sha2_password' cannot be loaded”をググって確認したところ、MySQL8.0.以降 のログイン認証方式のデフォルトがcaching_sha2_passwordが変更になり、Railsがその方式に対応していないことはわかりました。
[参考1](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)
[参考2](https://javascript-k.hatenablog.com/entry/mysql8_for_rails)

その為、下記記事を参考に
- 既存ユーザーの認証方式を変更
- /etc/my.cnfにてデフォルトの認証方式を変更
をそれぞれ試し、再度rails db:create RAILS_ENV=productionを実行しましたが、同様のエラーが出ております。
[参考3](https://qiita.com/ucan-lab/items/3ae911b7e13287a5b917#%E5%8E%9F%E5%9B%A0-mysql804-%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%AE%E8%AA%8D%E8%A8%BC%E6%96%B9%E5%BC%8F%E5%A4%89%E6%9B%B4)

## 現状の設定
mysqlバージョン
[![Image from Gyazo](https://i.gyazo.com/39bac987a6b9252bf0dc6eeaa19bf843.png)](https://gyazo.com/39bac987a6b9252bf0dc6eeaa19bf843)

mysqlのユーザー認証ブラグインとデフォルト認証プラグイン(変更済み)
[![Image from Gyazo](https://i.gyazo.com/866d8c5230ebb432110a65eb4a3655bb.png)](https://gyazo.com/866d8c5230ebb432110a65eb4a3655bb)

```
#config/database.yml 

default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysqlで設定したパスワードを記載
  host: RDSのエンドポイントを記載
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Voice_component_development

test:
  <<: *default
  database: Voice_component_test

production:
  <<: *default
  database: Voice_component_production


```
```
#  /etc/my.conf

# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/8.0/en/server-configuration-defaults.html

[mysqld]
#
# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
# innodb_buffer_pool_size = 128M
#
# Remove the leading "# " to disable binary logging
# Binary logging captures changes between backups and is enabled by
# default. It's default setting is log_bin=binlog
# disable_log_bin
#
# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
# join_buffer_size = 128M
# sort_buffer_size = 2M
# read_rnd_buffer_size = 2M
#
# Remove leading # to revert to previous value for default_authentication_plugin,
# this will increase compatibility with older clients. For background, see:
# https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
default-authentication-plugin=mysql_native_password

datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock

log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
```

**Comment by sayahaya** [comment]
上記講師フクハラさんに質問し、解決しました。
原因はRDSからmysqlを起動することを想定していましたが、EC2インスタンスからmysqlを起動し、そこでmysqlの認証プラグイン方式を変更したのでRDSインスタンスのmysqlの認証プラグイン方式は変更されていなかった為発生していたエラーでした。

## 解決方法
- EC2からRDSにログイン
EC2にログインした状態で下記を実行し、RDSにログイン　[参考1](https://dev.classmethod.jp/articles/sales-rds-ec2-session/)
```
$ mysql -u admin -p -h RDSのエンドポイントを張り付け
```

- mysqlにログインしuserを確認しconfig/database.ymlを変更
- rails db:create RAILS_ENV=productionを実行

→無事に作成完了

## その他指摘いただいた事項
- config/database.ymlのusernameやpassword,エンドポイントは他者から見られても分からないよう直書きは控える。(credentials.yml.encに記載するなど）
- config/database.ymlのデフォルトに本番環境のname, password,hostは書かないでproductionに記載するようにする。
→development, test環境はローカルで動かす為
- そもそもEC2にMysqlのクライアントだけを入れてサーバーを入れる必要がなかった[参考2](https://qiita.com/tamorieeeen/items/d9b2af588f1dfd43120d#4-mysql-community-client%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B)
