### ISSUE TITLE
ローカル環境でrails sを実行できない

### ISSUE THREAD

**Issue by sayahaya** [sayahaya/voice_component#46]
お疲れ様です。ローカル環境でしたところrails sを実行できず、またrails cとrails gを実行しようとしても同様のエラーが出てしまいます。共通しているエラー文を確認したところ、
```
(erb):2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```
と出ており、(erb):2とあるのでviewファイルの原因か？と思ったのですが該当するファイルなどが記載がなくどこがなく、念の為エラー文で調べたのですが、該当するような記事が見つからずアドバイスをいただけないでしょうか。

```
rails s実行時

(erb):2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `eval'
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `result'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/sources/yaml_source.rb:19:in `load'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:38:in `block in reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:48:in `load_files'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:56:in `load_and_set_settings'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:11:in `preload'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/railtie.rb:207:in `public_send'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/railtie.rb:207:in `method_missing'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/application.rb:96:in `inherited'
        from /Users/hayat/voice_component/config/application.rb:24:in `<module:VoiceComponent>'
        from /Users/hayat/voice_component/config/application.rb:22:in `<main>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4/lib/active_support/dependencies.rb:332:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:138:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:135:in `perform'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command/base.rb:69:in `perform'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /Users/hayat/voice_component/bin/rails:5:in `<top (required)>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/hayat/voice_component/bin/spring:10:in `block in <top (required)>'
        from <internal:kernel>:90:in `tap'
        from /Users/hayat/voice_component/bin/spring:7:in `<top (required)>'
        from bin/rails:2:in `load'
        from bin/rails:2:in `<main>'
```
```
rails c実行時

warning: parser/current is loading parser/ruby30, which recognizes
warning: 3.0.1-compliant syntax, but you are running 3.0.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(erb):2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `eval'
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `result'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/sources/yaml_source.rb:19:in `load'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:38:in `block in reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:48:in `load_files'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:56:in `load_and_set_settings'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:11:in `preload'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `public_send'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `method_missing'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/application.rb:96:in `inherited'
        from /Users/hayat/voice_component/config/application.rb:24:in `<module:VoiceComponent>'
        from /Users/hayat/voice_component/config/application.rb:22:in `<top (required)>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'

```
```
rails g実行時

warning: parser/current is loading parser/ruby30, which recognizes
warning: 3.0.1-compliant syntax, but you are running 3.0.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(erb):2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `eval'
        from /Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/erb.rb:905:in `result'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/sources/yaml_source.rb:19:in `load'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:38:in `block in reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/options.rb:37:in `reload!'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:48:in `load_files'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config.rb:56:in `load_and_set_settings'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:11:in `preload'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `public_send'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/railtie.rb:207:in `method_missing'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/config-3.1.0/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.1/lib/rails/application.rb:96:in `inherited'
        from /Users/hayat/voice_component/config/application.rb:24:in `<module:VoiceComponent>'
        from /Users/hayat/voice_component/config/application.rb:22:in `<top (required)>'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        from /Users/hayat/voice_component/vendor/bundle/ruby/3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/hayat/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'

```
## 試したこと

```
$ gem install bundler 
```
を実行したのち
```
$ bundle install --path vendor/bundle
```
を実行するもエラーは変わらずでした。

## 該当と思われるソースコード
調べて似たようなエラーの記事がありdatabase.ymlのエラーが原因ではないかと出ていたので載せます。
[参考](https://stackoverflow.com/questions/65496869/erb48in-main-undefined-method-for-nilnilclass-nomethoderror)

```
config/database.yml
  2 default: &default
  3   adapter: mysql2
  4   encoding: utf8mb4
  5   charset: utf8mb4
  6   collation: utf8mb4_general_ci
  7   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  8   username: root
  9   password:
 10   socket: /tmp/mysql.sock
 11 
 12 development:
 13   <<: *default
 14   database: Sample_development
 15 
 16 test:
 17   <<: *default
 18   database: Sample_test
 19 
 20 production:
 21   <<: *default
 22   database: <%= Rails.application.credentials.db[:database] %>
 23   username: <%= Rails.application.credentials.db[:username] %>
 24   password: <%= Rails.application.credentials.db[:password] %>
 25   host:     <%= Rails.application.credentials.db[:host] %>
 26 
```

**Comment by sayahaya** [comment]
一つ同じようなエラー記事を見つけたのですが、これが正解なのでしょうか。
[参考](https://stackoverflow.com/questions/65496869/erb48in-main-undefined-method-for-nilnilclass-nomethoderror)

**Comment by sayahaya** [comment]
上記の参考記事を確認する中でローカル環境のconfig以下にmaster.keyが入っていないことに気がつきました。（本番環境にデプロイするまではmaster.keyの存在、中身を確認しておりました）上記の根本的なエラーの原因かは分からないのですが、改めてローカル環境にmaster.keyを作成し、本番環境のmaster.keyの中身をコピーして保存しました。その後改めてrails sを実行したところ今度は別のエラーが出てきました
```
vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/message_encryptor.rb:203:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
```
下記記事を見たのですが原因は分からずの状態です・・・

[参考](https://qiita.com/suzy1031/items/64598d44b428ccd7abc5#rails-credentialsedit%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E5%8F%A9%E3%81%84%E3%81%9F%E3%82%89%E5%8B%9D%E6%89%8B%E3%81%AB%E9%8D%B5%E3%82%92%E7%94%9F%E6%88%90%E3%81%97%E3%81%A6-configmasterkey-%E3%81%AB%E4%BF%9D%E5%AD%98%E3%81%95%E3%82%8C%E3%81%9F)

**Comment by enda1111** [comment]
`config/credentials.yml.enc` は暗号化されていて、 対応する `master.key` が必要ですが、それが間違っていると発生するエラーっぽいです。
１度それが原因か確認したいので、
`config/credentials.yml.enc` と `master.key` を別のフォルダに移動してから、  `bundle exec rails credentials:edit` を実行して、新たに `config/credentials.yml.enc` と `master.key` を生成してから、 `rails s` で起動するか確認してみてください。

それで起動するようであれば、 別フォルダに移動しておいた`config/credentials.yml.enc` と `master.key` を元に戻して、 `master.key` に変な文字が入ってないか等確認してみるとよいかなと思います。

**Comment by sayahaya** [comment]
ご連絡ありがとうございます。
`config/credentials.yml.enc`と`master.key` を別のフォルダに移動してから、`bundle exec rails credentials:edit`を実行してみたのですが、その段階で同様のエラーが出てしまいました。railsのバージョンの問題などで発生することはあるのでしょうか？（特にいじった記憶はないのですが・・・）

**Comment by DaichiSaito** [comment]
先ほどの面談で伝え忘れましたが、master.keyは早急に変更した方が良いと思います。`git rm`してGit管理対象外にしたとは思いますが、Gitのコミットを追っていくと誰でも閲覧できてしまうので。誰でも好き勝手APIを利用できてしまい高額な請求が来る可能性もなきにしもあらずです。

@sayahaya

**Comment by DaichiSaito** [comment]
あとYahooじゃなくてGoogle使った方が良いかなとも思いました〜

**Comment by sayahaya** [comment]
@DaichiSaito 先ほどはご対応いただきありがとうございました。
> master.keyは早急に変更した方が良いと思います。git rmしてGit管理対象外にしたとは思いますが、Gitのコミットを追っていくと誰でも閲覧できてしまうので。誰でも好き勝手APIを利用できてしまい高額な請求が来る可能性もなきにしもあらずです。
上記は仰るとおり早急に改善したいと思います！

> あとYahooじゃなくてGoogle使った方が良いかなとも思いました〜
プライベートで使う時はYahooの方が使いやすかったので使い分けようとしてたのですがいつの間にかにごっちゃになってました！Googleにシフトしていくようにします！

**Comment by sayahaya** [comment]
@enda1111 どうしても自力で解決出来なかった為今回は技術面談で解決させていただきました。遅い時間にご対応いただきありがとうございました。

**Comment by enda1111** [comment]
@sayahaya 返事が遅くなってしまい、申し訳ありません。
解決されたようでよかったです〜

**Comment by sayahaya** [comment]
上記解決したので記載します。
## 原因
このエラーが起きる前に以前作業していたブランチに誤って入ってしまってからこのようなエラーが起き、
原因としてはconfig以下でcredentials.yml.encに対応するmaster.keyが存在しなかった為エラーが起きておりました。
恐らく以前にファイルを管理対象から除外する（master.keyは本来最初から.gitignoreに管理対象除外の記載があるはずなのに何故か反映されていた為）本来はターミナルで
```
git rm --cached [ファイル名]
```
と入力するところを
```
git rm [ファイル名]
```
と入力していた可能性があり、その為ローカルからファイルごと消えていたかもしれません（かなり前の作業なので記憶定かではありませんが・・・）

## 解決方法
master.keyのファイルと作成し、控えていたmaster.keyの中身をコピーし入力して保存。その後無事rails s他コマンド入力無事できるようになりました。

## 指摘・改善点
- 作業が終わったブランチは消すようにする。（このようなエラー発生を防ぐため）
